# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bdd939be15f50957e5e147b796f070e15c4763fb25af142a121b6566ed5c4088155c197c6359a72c0baa9a520a2a0714eb787d368699447dccee4b3c3aec507

test:
  secret_key_base: b6950d9e929edc624838954027a465c88a0a208da9e57f842d1eecc385a22a6bc8c0d6f9eb8a6a872163078b72dcaf1dacbd287fdced0d461d1c6f65c5cbdfa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
